<?php
namespace MuseDockPanel\Controllers;

use MuseDockPanel\View;

class ChangelogController
{
    public function index(): void
    {
        $versions = $this->getChangelog();

        View::render('changelog/index', [
            'layout' => 'main',
            'pageTitle' => 'Changelog',
            'versions' => $versions,
        ]);
    }

    private function getChangelog(): array
    {
        return [
            [
                'version' => '0.7.2',
                'date' => '2026-03-17',
                'badge' => 'success',
                'changes' => [
                    'added' => [
                        'es' => [
                            'Auto-deteccion de interfaces de red — El monitor detecta automaticamente las interfaces fisicas y WireGuard del servidor (eno1, eth0, enp0s3, wg0, etc.) sin necesidad de configuracion manual',
                            'Nombre de GPU en graficas — Las graficas de GPU muestran el modelo (ej. RTX 3090 Ti) en el titulo y en la leyenda de cada dataset',
                        ],
                        'en' => [
                            'Auto-detect network interfaces — Monitor automatically detects physical and WireGuard interfaces (eno1, eth0, enp0s3, wg0, etc.) without manual configuration',
                            'GPU name in charts — GPU charts show the model name (e.g. RTX 3090 Ti) in chart headers and dataset legends',
                        ],
                    ],
                    'fixed' => [
                        'es' => [
                            'update.sh systemd — Corregido placeholder __PANEL_PORT__ por __PANEL_INTERNAL_PORT__ que causaba 502 Bad Gateway tras actualizar',
                            'update.sh auto-relaunch — Si update.sh cambia durante git pull, se re-ejecuta automaticamente con la version nueva para evitar bugs del script viejo',
                            'GPU multi-host — detectGpus() ahora consulta la base de datos para hosts remotos en vez de ejecutar nvidia-smi local',
                            'Update banner — El banner de actualizaciones ahora comprueba GitHub automaticamente si no hay cache o ha expirado',
                        ],
                        'en' => [
                            'update.sh systemd — Fixed placeholder __PANEL_PORT__ to __PANEL_INTERNAL_PORT__ which caused 502 Bad Gateway after update',
                            'update.sh auto-relaunch — If update.sh changes during git pull, it re-executes itself with the new version to avoid stale script bugs',
                            'GPU multi-host — detectGpus() now queries the database for remote hosts instead of running local nvidia-smi',
                            'Update banner — Update banner now auto-checks GitHub if no cache exists or cache has expired',
                        ],
                    ],
                ],
            ],
            [
                'version' => '0.7.0',
                'date' => '2026-03-17',
                'badge' => 'success',
                'changes' => [
                    'added' => [
                        'es' => [
                            'Monitoring — Dashboard completo de monitorizacion con metricas de red, CPU y RAM en tiempo real',
                            'Graficas MRTG-style — Chart.js con RX/TX por interfaz (eth0, wg0), selectores de rango (1h/6h/24h/7d/30d/1y)',
                            'Historico 3 niveles — Datos raw (48h retencion), agregados por hora (90 dias), agregados diarios (ilimitado)',
                            'Health Score — Puntuacion 0-100 basada en CPU, RAM y trafico de red con penalizaciones ponderadas',
                            'Alertas — Alertas automaticas por CPU alta (>90%), RAM alta (>90%), trafico de red (>800Mbps) y GPU (temp >85C, util >95%)',
                            'Notificacion de alertas — Las alertas se envian por Email/Telegram via NotificationService con anti-spam (1 por tipo cada 5 min)',
                            'Acknowledge de alertas — Boton para marcar alertas como leidas, limpieza automatica de alertas acknowledged >30 dias',
                            'GPU Monitoring — Deteccion automatica de GPUs NVIDIA via nvidia-smi: utilizacion, memoria, temperatura y consumo',
                            'GPU Multi-GPU — Soporte para multiples GPUs con graficas independientes por GPU (util, memoria, temp, power)',
                            'Collector cron — Script bin/monitor-collector.php cada 30s con flock, delta calculation y limpieza automatica',
                            'Timezone en graficas — Las graficas muestran la hora de la zona configurada en Settings > Server (no la del navegador)',
                            'System Health — Nueva seccion en Settings con verificacion de crons, extensiones PHP, binarios y permisos de directorios',
                            'System Health Repair — Boton para reparar crons faltantes o vacios desde el panel',
                            'NTP status — Informacion de sincronizacion NTP en Settings > Server',
                            'PostgreSQL en UTC — La instancia del panel (5433) configurada en UTC para almacenamiento limpio de timestamps',
                            'Auto-Update — Sistema de actualizacion desde el panel: detecta nuevas versiones en GitHub, muestra changelog y actualiza con un click',
                            'Update banner — Banner en el header que notifica cuando hay una version nueva disponible',
                            'Settings > Updates — Pagina de actualizaciones con version actual/remota, boton de comprobar y actualizar, progreso en tiempo real',
                            'Update no-interactivo — Flag --auto en update.sh para ejecucion desde el panel sin prompts interactivos',
                        ],
                        'en' => [
                            'Monitoring — Full monitoring dashboard with real-time network, CPU and RAM metrics',
                            'MRTG-style charts — Chart.js with RX/TX per interface (eth0, wg0), range selectors (1h/6h/24h/7d/30d/1y)',
                            '3-tier history — Raw data (48h retention), hourly aggregates (90 days), daily aggregates (unlimited)',
                            'Health Score — 0-100 score based on CPU, RAM and network traffic with weighted penalties',
                            'Alerts — Automatic alerts for high CPU (>90%), high RAM (>90%), network traffic (>800Mbps) and GPU (temp >85C, util >95%)',
                            'Alert notifications — Alerts sent via Email/Telegram through NotificationService with anti-spam (1 per type per 5 min)',
                            'Alert acknowledge — Button to mark alerts as read, automatic cleanup of acknowledged alerts >30 days',
                            'GPU Monitoring — Automatic NVIDIA GPU detection via nvidia-smi: utilization, memory, temperature and power draw',
                            'GPU Multi-GPU — Support for multiple GPUs with independent charts per GPU (util, memory, temp, power)',
                            'Collector cron — bin/monitor-collector.php script every 30s with flock, delta calculation and automatic cleanup',
                            'Chart timezone — Charts display time in the timezone configured in Settings > Server (not browser timezone)',
                            'System Health — New Settings section with verification of crons, PHP extensions, binaries and directory permissions',
                            'System Health Repair — Button to repair missing or empty crons from the panel',
                            'NTP status — NTP synchronization info in Settings > Server',
                            'PostgreSQL on UTC — Panel instance (5433) configured in UTC for clean timestamp storage',
                            'Auto-Update — Panel update system: detects new versions on GitHub, shows changelog and updates with one click',
                            'Update banner — Header banner that notifies when a new version is available',
                            'Settings > Updates — Updates page with current/remote version, check and update buttons, real-time progress',
                            'Non-interactive update — --auto flag in update.sh for panel-triggered execution without interactive prompts',
                        ],
                    ],
                    'fixed' => [
                        'es' => [
                            'Orden de bases de datos — La seccion PostgreSQL Panel (5433) ahora aparece primera en la pagina de Databases',
                            'musedock_panel primera — Dentro de PostgreSQL Panel, la BD musedock_panel aparece primera en la lista',
                            'Timezone en graficas — Corregido bug donde las graficas mostraban hora del navegador en vez de la zona del servidor',
                            'PostgreSQL timezone — Cambiado de Europe/Berlin a UTC para evitar ambiguedad en timestamps almacenados',
                            'certbot eliminado de Health — Caddy gestiona SSL internamente, certbot no es necesario',
                            'Monitor cron en instalador — El cron musedock-monitor se instala automaticamente en install.sh y update.sh',
                        ],
                        'en' => [
                            'Database ordering — PostgreSQL Panel (5433) section now appears first on the Databases page',
                            'musedock_panel first — Within PostgreSQL Panel, musedock_panel DB appears first in the list',
                            'Chart timezone — Fixed bug where charts showed browser timezone instead of server timezone',
                            'PostgreSQL timezone — Changed from Europe/Berlin to UTC to avoid timestamp ambiguity',
                            'certbot removed from Health — Caddy manages SSL internally, certbot is not needed',
                            'Monitor cron in installer — The musedock-monitor cron is automatically installed in install.sh and update.sh',
                        ],
                    ],
                ],
            ],
            [
                'version' => '0.6.0',
                'date' => '2026-03-17',
                'badge' => 'success',
                'changes' => [
                    'added' => [
                        'es' => [
                            'Cluster tabs — La página de Cluster se reorganizó en 6 pestañas: Estado, Nodos, Archivos, Failover, Configuración, Cola',
                            'Sincronización Completa — Botón orquestador en pestaña Estado que ejecuta en secuencia: hostings (API) → archivos (rsync) → bases de datos (dump) → certificados SSL',
                            'Endpoint full-sync — POST /settings/cluster/full-sync lanza proceso en background con progreso en tiempo real via AJAX polling',
                            'DB dump sync (Nivel 1) — Sincronización simple de bases de datos entre master y slave usando pg_dump/mysqldump comprimidos con gzip. Se restauran automáticamente en el slave con DROP + CREATE + IMPORT',
                            'DB dump en sync manual — La sincronización manual de archivos ahora también incluye dump y restauración de bases de datos si está habilitado',
                            'DB dump periódico — El cron filesync-worker incluye dumps de BD cada intervalo si está habilitado. Se omite automáticamente si streaming replication (Nivel 2) está activo',
                            'isStreamingActive() — Método en ReplicationService que detecta si la replicación streaming de PostgreSQL o MySQL está activa',
                            'restore-db-dumps — Acción en la API del cluster para que el slave restaure los dumps recibidos. Crea usuarios de BD si no existen',
                            'Backup pre-replicación — Al convertir un servidor a slave de streaming replication, se crea backup automático de todas las bases de datos en /var/backups/musedock/pre-replication/ con timestamp',
                            'Modal convert-to-slave mejorado — Aviso en rojo explicando que se borrarán TODAS las bases de datos locales, lista las BD afectadas, checkbox de backup automático activado por defecto',
                            'Failover con select de nodos — El campo de IP manual para degradar a slave se reemplazó por un selector desplegable de nodos conectados',
                            'Failover con password — Promover a Master y Degradar a Slave requieren contraseña de administrador con validación AJAX y modales explicativos',
                            'System Users — Sección de solo lectura mostrando todos los usuarios del sistema Linux (UID, grupos, shell, home)',
                            'Hosting repair on re-sync — Si un hosting ya existe en el slave, se repara (UID, shell, grupos, password hash, caddy_route_id) en vez de saltarlo',
                            'SSL cert detection en slave — El panel detecta certificados SSL copiados del master via Caddy admin API y filesystem',
                            'Sync progress modal — Modal con barra de progreso, cronómetro y dominio actual durante la sincronización. Persiste tras recargar página',
                            'Auto-configurar replicación en slave — Botón "Convertir este nodo en Slave de X" con modal de advertencia, backup automático y verificación de contraseña',
                            'Nodo virtual en slave — Si el slave no tiene nodos de cluster registrados pero conoce la IP del master, muestra un nodo virtual para auto-configurar',
                        ],
                        'en' => [
                            'Cluster tabs — Cluster page reorganized into 6 tabs: Status, Nodes, Files, Failover, Config, Queue',
                            'Full Sync — Orchestrator button in Status tab that runs in sequence: hostings (API) → files (rsync) → databases (dump) → SSL certificates',
                            'Full-sync endpoint — POST /settings/cluster/full-sync launches background process with real-time AJAX progress polling',
                            'DB dump sync (Level 1) — Simple database sync between master and slave using pg_dump/mysqldump compressed with gzip. Auto-restored on slave with DROP + CREATE + IMPORT',
                            'DB dump in manual sync — Manual file sync now also includes database dump and restore if enabled',
                            'Periodic DB dump — The filesync-worker cron includes DB dumps each interval if enabled. Automatically skipped if streaming replication (Level 2) is active',
                            'isStreamingActive() — ReplicationService method that detects if PostgreSQL or MySQL streaming replication is active',
                            'restore-db-dumps — Cluster API action for the slave to restore received dumps. Creates DB users if they don\'t exist',
                            'Pre-replication backup — When converting a server to streaming slave, automatically backs up all databases to /var/backups/musedock/pre-replication/ with timestamp',
                            'Improved convert-to-slave modal — Red warning explaining ALL local databases will be deleted, lists affected DBs, auto-backup checkbox enabled by default',
                            'Failover with node selector — Manual IP input for demote-to-slave replaced by dropdown of connected nodes',
                            'Failover with password — Promote to Master and Demote to Slave require admin password with AJAX validation and detailed modals',
                            'System Users — Read-only section showing all Linux system users (UID, groups, shell, home)',
                            'Hosting repair on re-sync — If a hosting already exists on slave, repairs it (UID, shell, groups, password hash, caddy_route_id) instead of skipping',
                            'SSL cert detection on slave — Panel detects SSL certificates copied from master via Caddy admin API and filesystem',
                            'Sync progress modal — Modal with progress bar, timer and current domain during sync. Persists after page reload',
                            'Auto-configure replication on slave — "Convert this node to Slave of X" button with warning modal, auto-backup and password verification',
                            'Virtual node on slave — If slave has no cluster nodes but knows master IP, shows a virtual node for auto-configure',
                        ],
                    ],
                    'fixed' => [
                        'es' => [
                            'Tildes en español — Corregidas todas las tildes faltantes en la página de Cluster (más de 50 correcciones)',
                            'Caddy Route N/A en slave — caddy_route_id ahora se incluye en el payload de sincronización de hostings',
                            'JSON sync modal — Corregido mismatch de campos entre backend (synced/failed) y frontend (ok_count/fail_count)',
                            'filesync-run.php bootstrap — Corregido error de archivo no encontrado usando bootstrap inline',
                            'rsync --delete en certs — Los certificados del slave ya no se borran al sincronizar',
                            'DROP DATABASE con conexiones activas — Añadido pg_terminate_backend + DROP DATABASE WITH (FORCE) con fallback para PG < 13',
                            'Session key en verify-admin-password — Corregido $_SESSION[admin_id] inexistente por $_SESSION[panel_user][id]',
                            'Auto-configure en slave sin nodos — El botón de auto-configurar ahora aparece en el slave usando nodo virtual del master',
                        ],
                        'en' => [
                            'Spanish tildes — Fixed all missing accents across the Cluster page (50+ corrections)',
                            'Caddy Route N/A on slave — caddy_route_id now included in hosting sync payload',
                            'JSON sync modal — Fixed field mismatch between backend (synced/failed) and frontend (ok_count/fail_count)',
                            'filesync-run.php bootstrap — Fixed file not found error using inline bootstrap',
                            'rsync --delete on certs — Slave certificates no longer deleted during sync',
                            'DROP DATABASE with active connections — Added pg_terminate_backend + DROP DATABASE WITH (FORCE) with PG < 13 fallback',
                            'Session key in verify-admin-password — Fixed non-existent $_SESSION[admin_id] to $_SESSION[panel_user][id]',
                            'Auto-configure on slave without nodes — Auto-configure button now appears on slave using virtual master node',
                        ],
                    ],
                ],
            ],
            [
                'version' => '0.5.3',
                'date' => '2026-03-16',
                'badge' => 'success',
                'changes' => [
                    'added' => [
                        'es' => [
                            'File Sync — Sincronización de archivos entre master y slaves via SSH (rsync) o HTTPS (API), con cron worker automático',
                            'File Sync SSL certs — Sincronización de certificados SSL de Caddy entre nodos con propiedad correcta (caddy:caddy)',
                            'File Sync ownership — rsync con --chown y HTTPS con owner_user para corregir UIDs entre servidores',
                            'File Sync UI — Botones funcionales en Cluster: generar clave SSH, instalar en nodo, test SSH, sincronizar ahora, verificar DB host',
                            'SSH info banner — Nota explicativa en la página de Cluster con el flujo de 3 pasos para configurar claves SSH',
                            'Firewall protocolos — Los protocolos ahora se muestran como texto (TCP, UDP, ICMP, ALL) en vez de números',
                            'Firewall descripción — Nueva columna "Descripción" en iptables mostrando estado (RELATED,ESTABLISHED, etc.)',
                            'Firewall protocolo ALL — Opción "Todos" en el selector de protocolo para reglas sin puerto específico',
                            'Cifrado Telegram — Token de Telegram cifrado con AES-256-CBC en panel_settings',
                            'Cifrado SMTP — Password SMTP cifrado con AES-256-CBC en panel_settings',
                            'Instalador Update — Nuevo modo "Actualizar" (opción 4) que aplica cambios incrementales sin reinstalar',
                            'Instalador filesync cron — El cron musedock-filesync se instala automáticamente con el instalador',
                            'SSL cert auto-fill — La ruta de certificados SSL se auto-rellena si se detecta Caddy',
                        ],
                        'en' => [
                            'File Sync — File synchronization between master and slaves via SSH (rsync) or HTTPS (API), with automatic cron worker',
                            'File Sync SSL certs — Caddy SSL certificate sync between nodes with correct ownership (caddy:caddy)',
                            'File Sync ownership — rsync with --chown and HTTPS with owner_user to fix UIDs between servers',
                            'File Sync UI — Working buttons in Cluster: generate SSH key, install on node, test SSH, sync now, verify DB host',
                            'SSH info banner — Explanatory note in Cluster page with 3-step flow for configuring SSH keys',
                            'Firewall protocols — Protocols now shown as text (TCP, UDP, ICMP, ALL) instead of numbers',
                            'Firewall description — New "Description" column in iptables showing state (RELATED,ESTABLISHED, etc.)',
                            'Firewall protocol ALL — "All" option in protocol selector for rules without specific port',
                            'Telegram encryption — Telegram token encrypted with AES-256-CBC in panel_settings',
                            'SMTP encryption — SMTP password encrypted with AES-256-CBC in panel_settings',
                            'Installer Update — New "Update" mode (option 4) that applies incremental changes without reinstalling',
                            'Installer filesync cron — The musedock-filesync cron is automatically installed with the installer',
                            'SSL cert auto-fill — SSL certificate path auto-fills if Caddy is detected',
                        ],
                    ],
                    'fixed' => [
                        'es' => [
                            'SMTP cifrado — Corregido tipo de cifrado (SSL→TLS/STARTTLS) y typo en dirección From',
                            'Firewall IPs — Las reglas muestran IPs numéricas en vez de hostnames (flag -n)',
                            'File Sync permisos — Los archivos sincronizados mantienen el propietario correcto en el slave',
                            'JS funciones faltantes — Añadidas 7 funciones JavaScript que faltaban en la UI de File Sync/Cluster',
                            'JS IDs inconsistentes — Corregidos IDs de HTML que no coincidían con los selectores de JavaScript',
                        ],
                        'en' => [
                            'SMTP encryption — Fixed encryption type (SSL→TLS/STARTTLS) and typo in From address',
                            'Firewall IPs — Rules show numeric IPs instead of hostnames (-n flag)',
                            'File Sync permissions — Synced files maintain correct owner on slave',
                            'Missing JS functions — Added 7 missing JavaScript functions in File Sync/Cluster UI',
                            'Inconsistent JS IDs — Fixed HTML IDs that didn\'t match JavaScript selectors',
                        ],
                    ],
                ],
            ],
            [
                'version' => '0.5.2',
                'date' => '2026-03-16',
                'badge' => 'success',
                'changes' => [
                    'added' => [
                        'es' => [
                            'Notificaciones — Nueva pestaña Settings > Notificaciones con Email (SMTP/PHP mail) y Telegram unificados',
                            'Email SMTP avanzado — Selector de cifrado STARTTLS/SSL/Ninguno, test de envio inline con AJAX',
                            'Email destinatario inteligente — Por defecto usa el email del perfil del admin, con override manual opcional',
                            'Firewall editable — Las reglas del firewall ahora se pueden editar (antes solo eliminar), modal de edicion con todos los campos',
                            'Firewall interfaces de red — Muestra todas las interfaces del servidor con IP real (ya no 127.0.0.1)',
                            'Firewall direccion — Columna IN/OUT visible en el listado de reglas',
                            'Databases multi-instancia — Vista de BBDD muestra PostgreSQL Hosting (5432, replicable), PostgreSQL Panel (5433) y MySQL agrupados',
                            'Databases reales — Lista todas las bases de datos reales del sistema, no solo las gestionadas por el panel',
                            'Activity Log filtros — Busqueda por texto, filtro por accion y por admin, paginacion de 50 registros',
                            'Activity Log limpieza — Boton para limpiar logs antiguos (7/30/90/180 dias) y vaciar todo con verificacion de password',
                            'Visor de logs limpieza — Boton para vaciar archivos de log individuales con confirmacion SweetAlert',
                            'Caddy access logs — Los logs de acceso de Caddy por dominio ahora aparecen en el visor de logs',
                        ],
                        'en' => [
                            'Notifications — New Settings > Notifications tab with unified Email (SMTP/PHP mail) and Telegram',
                            'Advanced SMTP email — STARTTLS/SSL/None encryption selector, inline send test with AJAX',
                            'Smart recipient email — Defaults to admin profile email, with optional manual override',
                            'Editable firewall — Firewall rules can now be edited (previously delete-only), edit modal with all fields',
                            'Firewall network interfaces — Shows all server interfaces with real IP (no longer 127.0.0.1)',
                            'Firewall direction — IN/OUT column visible in rule listing',
                            'Multi-instance databases — DB view shows PostgreSQL Hosting (5432, replicable), PostgreSQL Panel (5433) and MySQL grouped',
                            'Real databases — Lists all real system databases, not just panel-managed ones',
                            'Activity Log filters — Text search, action filter, admin filter, 50-record pagination',
                            'Activity Log cleanup — Button to clean old logs (7/30/90/180 days) and clear all with password verification',
                            'Log viewer cleanup — Button to truncate individual log files with SweetAlert confirmation',
                            'Caddy access logs — Per-domain Caddy access logs now appear in the log viewer',
                        ],
                    ],
                    'fixed' => [
                        'es' => [
                            'Firewall reglas DENY — Las reglas DENY/REJECT ahora aparecen correctamente en el listado (regex corregido)',
                            'Firewall borde blanco — Eliminado borde blanco de la tabla de interfaces de red',
                            'Email remitente — El From por defecto ahora usa el email del admin (antes usaba panel@hostname)',
                            'Email destinatario — Corregido "No hay email configurado" que ocurria porque la query filtraba por role=admin en vez de superadmin',
                            'PHP mail() error claro — Muestra mensaje especifico cuando sendmail/postfix no esta instalado',
                            'Session key password — Corregido $_SESSION[admin_id] inexistente por $_SESSION[panel_user][id] en verificacion de password (Vaciar todo logs y Eliminar BD)',
                            'Icono busqueda invisible — Añadido color blanco al icono de lupa en Activity Log (era oscuro sobre fondo oscuro)',
                            'Notificaciones migradas — Las config de SMTP/Telegram se movieron de Cluster a la nueva pestaña Notificaciones con migracion automatica de claves',
                        ],
                        'en' => [
                            'Firewall DENY rules — DENY/REJECT rules now appear correctly in the listing (regex fixed)',
                            'Firewall white border — Removed white border from network interfaces table',
                            'Sender email — Default From now uses admin email (was using panel@hostname)',
                            'Recipient email — Fixed "No email configured" caused by query filtering role=admin instead of superadmin',
                            'PHP mail() clear error — Shows specific message when sendmail/postfix is not installed',
                            'Session key password — Fixed non-existent $_SESSION[admin_id] to $_SESSION[panel_user][id] in password verification (Clear all logs and Delete DB)',
                            'Invisible search icon — Added white color to search icon in Activity Log (was dark on dark background)',
                            'Notifications migrated — SMTP/Telegram config moved from Cluster to new Notifications tab with automatic key migration',
                        ],
                    ],
                ],
            ],
            [
                'version' => '0.5.1',
                'date' => '2026-03-17',
                'badge' => 'success',
                'changes' => [
                    'added' => [
                        'es' => [
                            'Replicacion 3 modos — Master manual (solo config, sin credenciales), Slave manual, Auto-cluster',
                            'Usuarios de replicacion — CRUD con password autogenerado y boton copiar, se muestra una sola vez',
                            'IPs autorizadas — Gestion de pg_hba.conf y MySQL GRANT desde el panel, añadir/eliminar IPs de slaves',
                            'Auto-configuracion cluster — El slave pide credenciales al master via API, pg_basebackup automatico',
                            'Dashboard procesos — Click en card CPU/RAM abre modal con top procesos en tiempo real (auto-refresh 3s)',
                            'Dashboard monitor — Tabla de procesos con PID, usuario, CPU%, RAM%, RSS, estado, comando, barras de color',
                        ],
                        'en' => [
                            'Replication 3 modes — Manual master (config only, no credentials), manual slave, auto-cluster',
                            'Replication users — CRUD with auto-generated password and copy button, shown once only',
                            'Authorized IPs — pg_hba.conf and MySQL GRANT management from the panel, add/remove slave IPs',
                            'Cluster auto-configure — Slave requests credentials from master via API, automatic pg_basebackup',
                            'Dashboard processes — Click CPU/RAM card opens real-time top processes modal (auto-refresh 3s)',
                            'Dashboard monitor — Process table with PID, user, CPU%, RAM%, RSS, state, command, color bars',
                        ],
                    ],
                    'fixed' => [
                        'es' => [
                            'Replicacion UX — Eliminado formulario confuso de credenciales al activar master',
                            'Rutas replicacion — Corregidas todas las rutas de formularios (404 en version anterior)',
                            'Vista replicacion — Corregido View::csrfField() inexistente por View::csrf()',
                        ],
                        'en' => [
                            'Replication UX — Removed confusing credentials form when activating master',
                            'Replication routes — Fixed all form routes (404 in previous version)',
                            'Replication view — Fixed non-existent View::csrfField() to View::csrf()',
                        ],
                    ],
                ],
            ],
            [
                'version' => '0.5.0',
                'date' => '2026-03-16',
                'badge' => 'success',
                'changes' => [
                    'added' => [
                        'es' => [
                            'Cluster multi-servidor — Arquitectura master/slave entre paneles con API bidireccional y token Bearer',
                            'API de Cluster — Endpoints /api/cluster/status, heartbeat y action para comunicacion entre nodos',
                            'Sincronizacion de hostings — Cola cluster_queue para propagar creacion/eliminacion/suspension entre nodos',
                            'Heartbeat y monitoreo — Deteccion automatica de nodos caidos, alertas por email SMTP y Telegram',
                            'Failover — Promover slave a master y degradar master a slave desde el panel',
                            'Worker cron — bin/cluster-worker.php para procesar cola, heartbeats y alertas automaticas',
                            'Instalador dual PostgreSQL — Cluster dedicado en puerto 5433, migracion automatica desde 5432',
                            'Roles de replicacion por motor — repl_pg_role y repl_mysql_role independientes',
                        ],
                        'en' => [
                            'Multi-server cluster — Master/slave architecture between panels with bidirectional API and Bearer token',
                            'Cluster API — /api/cluster/status, heartbeat and action endpoints for inter-node communication',
                            'Hosting sync — cluster_queue for propagating account creation/deletion/suspension across nodes',
                            'Heartbeat and monitoring — Automatic detection of unreachable nodes, email SMTP and Telegram alerts',
                            'Failover — Promote slave to master and demote master to slave from the panel',
                            'Cron worker — bin/cluster-worker.php for queue processing, heartbeats and automatic alerts',
                            'Dual PostgreSQL installer — Dedicated cluster on port 5433, automatic migration from 5432',
                            'Per-engine replication roles — Independent repl_pg_role and repl_mysql_role',
                        ],
                    ],
                    'fixed' => [
                        'es' => [
                            'Instalador Caddy HTTPS — tls internal on_demand, resuelto conflicto con nginx en puerto 80',
                            'Instalador verify mode — set +e para que los checks no maten el script, 10 secciones diagnostico',
                            'Instalador crons — Cron cluster-worker cada minuto, pg_dump backup cada hora con retencion 48h',
                        ],
                        'en' => [
                            'Installer Caddy HTTPS — tls internal on_demand, resolved nginx port 80 conflict',
                            'Installer verify mode — set +e so checks don\'t kill the script, 10 diagnostic sections',
                            'Installer crons — Cluster-worker cron every minute, hourly pg_dump backup with 48h retention',
                        ],
                    ],
                ],
            ],
            [
                'version' => '0.4.0',
                'date' => '2026-03-15',
                'badge' => 'success',
                'changes' => [
                    'added' => [
                        'es' => [
                            'Replicacion avanzada — Multiples slaves por master, IPs dual (primaria + fallback WireGuard)',
                            'Replicacion sincrona/asincrona — Modo configurable por slave en PostgreSQL',
                            'Replicacion logica PostgreSQL — Seleccionar bases de datos a replicar en vez de todo el cluster',
                            'GTID MySQL — Soporte GTID-based replication, mostrar GTID position en monitor',
                            'Monitor multi-slave — Estado individual por slave con lag, bytes pendientes, conexion activa',
                            'WireGuard VPN — Instalar, configurar wg0, CRUD de peers, generar claves y config remota, ping/latencia',
                            'Firewall — Auto-deteccion UFW/iptables, ver/añadir/eliminar reglas, boton de emergencia, sugerencias',
                        ],
                        'en' => [
                            'Advanced replication — Multiple slaves per master, dual IPs (primary + WireGuard fallback)',
                            'Sync/async replication — Configurable mode per slave in PostgreSQL',
                            'PostgreSQL logical replication — Select specific databases to replicate instead of full cluster',
                            'MySQL GTID — GTID-based replication support, show GTID position in monitor',
                            'Multi-slave monitor — Individual slave status with lag, pending bytes, active connection',
                            'WireGuard VPN — Install, configure wg0, peer CRUD, generate keys and remote config, ping/latency',
                            'Firewall — Auto-detect UFW/iptables, view/add/delete rules, emergency button, suggestions',
                        ],
                    ],
                ],
            ],
            [
                'version' => '0.3.0',
                'date' => '2026-03-15',
                'badge' => 'success',
                'changes' => [
                    'added' => [
                        'es' => [
                            'Backups — Backup/restore por cuenta (archivos + BD MySQL/PostgreSQL), descarga, eliminacion con confirmacion',
                            'Fail2Ban — Ver jails activos, IPs baneadas, desbloquear IPs desde el panel',
                            'Visor de logs — Logs de Caddy, FPM, cuentas y sistema con navegacion por archivo',
                            'Base de datos PostgreSQL — Crear/eliminar BD PostgreSQL por cuenta desde el panel',
                            'Base de datos protegida — La BD del sistema (musedock_panel) se muestra como protegida y no se puede borrar',
                            'Confirmacion con password — Borrar BD y backups requiere password del admin',
                            'Changelog — Pagina de versiones con toggle ES/EN, version clickeable en sidebar',
                        ],
                        'en' => [
                            'Backups — Per-account backup/restore (files + MySQL/PostgreSQL DB), download, deletion with confirmation',
                            'Fail2Ban — View active jails, banned IPs, unblock IPs from the panel',
                            'Log browser — Caddy, FPM, account and system logs with file navigation',
                            'PostgreSQL databases — Create/delete PostgreSQL databases per account from the panel',
                            'Protected database — System DB (musedock_panel) shown as protected and cannot be deleted',
                            'Password confirmation — Deleting databases and backups requires admin password',
                            'Changelog — Version history page with ES/EN toggle, clickable version in sidebar',
                        ],
                    ],
                ],
            ],
            [
                'version' => '0.2.0',
                'date' => '2026-03-15',
                'badge' => 'info',
                'changes' => [
                    'added' => [
                        'es' => [
                            'Settings > Servidor — Info del servidor, zona horaria configurable, dominio del panel, selector HTTP/HTTPS',
                            'Settings > PHP — Configuracion global de php.ini por version, lista de extensiones, reinicio FPM',
                            'Settings > SSL/TLS — Certificados activos de Caddy, politicas TLS, info Let\'s Encrypt',
                            'Settings > Seguridad — IPs permitidas en vivo, sesiones activas, info de cookies',
                            'PHP por cuenta — memory_limit, upload_max, post_max, max_execution_time por hosting account',
                            'Gestion de bases de datos MySQL — Crear/eliminar BD MySQL por cuenta, usuarios con prefijo',
                            'Tabla panel_settings — Almacen clave-valor para configuracion del panel',
                            'Tabla servers — Preparacion para clustering (localhost por defecto)',
                            'Campo server_id en hosting_accounts — Preparacion para multi-servidor',
                            'Instalador HTTPS — Caddy como reverse proxy con certificado autofirmado',
                            'Instalador i18n — Seleccion de idioma ES/EN, todos los textos traducidos',
                            'Instalador firewall — Deteccion UFW/iptables, estado del puerto',
                            'Modo verificacion — Health check sin tocar nada',
                            'Desinstalador — bin/uninstall.sh con confirmaciones paso a paso',
                        ],
                        'en' => [
                            'Settings > Server — Server info, configurable timezone, panel domain, HTTP/HTTPS selector',
                            'Settings > PHP — Global php.ini config per version, extension list, FPM restart',
                            'Settings > SSL/TLS — Active Caddy certificates, TLS policies, Let\'s Encrypt info',
                            'Settings > Security — Live allowed IPs, active sessions, cookie info',
                            'Per-account PHP — memory_limit, upload_max, post_max, max_execution_time per hosting account',
                            'MySQL database management — Create/delete MySQL databases per account, prefixed users',
                            'panel_settings table — Key-value store for panel configuration',
                            'servers table — Clustering preparation (localhost default)',
                            'server_id field in hosting_accounts — Multi-server preparation',
                            'Installer HTTPS — Caddy as reverse proxy with self-signed certificate',
                            'Installer i18n — ES/EN language selection, all texts translated',
                            'Installer firewall — UFW/iptables detection, port status',
                            'Verify mode — Health check without changing anything',
                            'Uninstaller — bin/uninstall.sh with step-by-step confirmations',
                        ],
                    ],
                    'fixed' => [
                        'es' => [
                            'Login HTTP — Cookie Secure solo en HTTPS (antes bloqueaba login en HTTP)',
                            'HSTS condicional — Header solo en conexiones HTTPS',
                            'Favicon — Eliminado punto verde, solo muestra la M',
                            'Health check — Fallback multi-URL (HTTPS, HTTP interno, HTTP directo)',
                            'Firewall iptables — Deteccion correcta de policy DROP y reglas ACCEPT all',
                        ],
                        'en' => [
                            'HTTP login — Secure cookie flag only on HTTPS (was blocking login on HTTP)',
                            'Conditional HSTS — Header only on HTTPS connections',
                            'Favicon — Removed green dot, shows only the M',
                            'Health check — Multi-URL fallback (HTTPS, internal HTTP, direct HTTP)',
                            'Firewall iptables — Correct policy DROP detection and ACCEPT all rules',
                        ],
                    ],
                ],
            ],
            [
                'version' => '0.1.0',
                'date' => '2026-03-14',
                'badge' => 'secondary',
                'changes' => [
                    'added' => [
                        'es' => [
                            'Dashboard — CPU, RAM, disco, cuentas de hosting, info del sistema',
                            'Hosting Accounts — Crear, suspender, activar, eliminar cuentas con usuario Linux, pool FPM y ruta Caddy',
                            'Dominios — Gestion de dominios por cuenta, verificacion DNS, alias',
                            'Clientes — Vincular cuentas de hosting a clientes',
                            'Settings > Servicios — Iniciar/detener/reiniciar Caddy, MySQL, PostgreSQL, PHP-FPM',
                            'Settings > Cron — Crear, editar, eliminar tareas cron por usuario',
                            'Settings > Caddy — Visor de rutas API, politicas TLS, config raw JSON',
                            'Activity Log — Historial completo de acciones del admin',
                            'Perfil — Cambiar usuario, email, contraseña',
                            'Setup wizard — Asistente de primera configuracion',
                            'Tema oscuro — Interfaz moderna con Bootstrap 5',
                            'Seguridad — CSRF, sesiones seguras, prevencion de inyeccion, headers de seguridad',
                            'Instalador automatizado — Deteccion de OS, instalacion de dependencias',
                            'Servicio systemd — Restart automatico',
                        ],
                        'en' => [
                            'Dashboard — CPU, RAM, disk, hosting accounts, system info',
                            'Hosting Accounts — Create, suspend, activate, delete accounts with Linux user, FPM pool, and Caddy route',
                            'Domains — Domain management per account, DNS verification, aliases',
                            'Customers — Link hosting accounts to customers',
                            'Settings > Services — Start/stop/restart Caddy, MySQL, PostgreSQL, PHP-FPM',
                            'Settings > Cron — Create, edit, delete cron jobs per user',
                            'Settings > Caddy — API routes viewer, TLS policies, raw JSON config',
                            'Activity Log — Full admin action history',
                            'Profile — Change username, email, password',
                            'Setup wizard — First-time configuration assistant',
                            'Dark theme — Modern interface with Bootstrap 5',
                            'Security — CSRF, secure sessions, injection prevention, security headers',
                            'Automated installer — OS detection, dependency installation',
                            'Systemd service — Automatic restart',
                        ],
                    ],
                ],
            ],
        ];
    }
}
