<?php use MuseDockPanel\View; $d=$directMcp; ?>
<div class="card mb-4"><div class="card-header"><h5 class="mb-0">Conexión MCP directa · ChatGPT, Claude y otros clientes</h5></div><div class="card-body">
<p>Un subdominio HTTPS independiente en el puerto 443, sin túnel OpenAI. OAuth es obligatorio y cada cliente tiene sus propios permisos y tokens.</p>
<p><span class="badge <?= $d['enabled']?'bg-success':'bg-secondary' ?>"><?= $d['enabled']?'Activada':'Desactivada' ?></span> · Permisos disponibles: <strong>lectura y escritura con aprobación</strong> · configurados por cliente</p>
<?php if(!$d['enabled']): ?><div class="alert alert-info">Preparación y pruebas. Guardar estos datos no publica el MCP ni crea el DNS. La activación pública queda pendiente de tu confirmación después de revisar las pruebas.</div><?php endif; ?>
<?php if(!empty($directMcpCredentials)): ?><div class="mcp-section" id="mcp-new-credentials">
<div class="d-flex justify-content-between flex-wrap gap-2 mb-2"><strong>Credenciales del nuevo cliente</strong><button type="button" class="btn btn-sm btn-outline-secondary" data-mcp-dismiss="mcp-new-credentials">Cerrar y retirar de esta página</button></div>
<p class="small text-warning">El secreto se muestra una sola vez. Cópialo en tu asistente antes de cerrar o salir de esta página.</p>
<?php foreach(['id'=>'ID del cliente','secret'=>'Secreto del cliente'] as $key=>$label): ?>
<label class="form-label" for="direct-new-<?= $key ?>"><?= $label ?></label><div class="input-group mb-3"><input id="direct-new-<?= $key ?>" class="form-control font-monospace" type="<?= $key==='secret'?'password':'text' ?>" readonly autocomplete="off" value="<?= View::e($directMcpCredentials[$key]) ?>">
<?php if($key==='secret'): ?><button class="btn btn-outline-secondary" type="button" data-mcp-toggle="direct-new-secret">Mostrar</button><?php endif; ?><button class="btn btn-outline-info" type="button" data-mcp-copy="direct-new-<?= $key ?>">Copiar</button></div><?php endforeach; ?>
</div><?php endif; ?>
<details class="mcp-section" <?= !$d['issuer']?'open':'' ?>><summary>Configuración del acceso HTTPS</summary>
<form method="post" action="/settings/mcp/direct/save" class="mb-3"><?= View::csrf() ?><input type="hidden" name="action" value="configure">
<div class="row g-3"><div class="col-md-6"><label class="form-label">Subdominio HTTPS dedicado</label><input class="form-control" type="url" name="issuer" value="<?= View::e($d['issuer']) ?>" placeholder="https://mcp.mortadelo.screenart.es" required <?= $d['enabled']?'disabled':'' ?>></div>
<div class="col-md-6"><label class="form-label">URL privada del panel para autorizar</label><input class="form-control" type="url" name="panel_url" value="<?= View::e($d['panel_url']) ?>" placeholder="https://mortadelo.screenart.es:8444" required <?= $d['enabled']?'disabled':'' ?>></div></div>
<button class="btn btn-outline-primary mt-3" <?= $d['enabled']?'disabled':'' ?>>Guardar configuración</button></form></details>
<?php if($d['issuer']): ?><p>URL para añadir en el asistente: <code><?= View::e($d['issuer']) ?>/mcp</code>. Registro OAuth: <strong>tu propio cliente</strong>; autenticación del token: <code>client_secret_basic</code>; ámbitos según los permisos del cliente: <code>musedock:read</code>, <code>musedock:write</code> y, para DNS, <code>musedock:dns</code>. Sin OIDC ni registro dinámico. Si aún no hay clientes registrados, el descubrimiento no concede acceso a herramientas ni datos.</p><?php endif; ?>
<?php if($d['enabled']): ?>
<details class="mcp-section" <?= !$d['clients']?'open':'' ?>><summary>Conectar una cuenta de ChatGPT</summary>

<p class="small mb-2">Añade en ChatGPT la URL <code><?= View::e($d['issuer']) ?>/mcp</code>, elige OAuth y «cliente definido por el usuario». Comprueba que la devolución de llamada de ChatGPT coincide con la de este formulario; si muestra otra, cópiala aquí antes de crear las credenciales.</p>
<form method="post" action="/settings/mcp/direct/save"><?= View::csrf() ?><input type="hidden" name="action" value="register"><input type="hidden" name="provider" value="openai"><input type="hidden" name="name" value="ChatGPT">
<label class="form-label" for="chatgpt-direct-callback">Devolución de llamada de ChatGPT</label><input class="form-control mb-2" id="chatgpt-direct-callback" type="url" name="redirect_uri" value="https://chatgpt.com/connector_platform_oauth_redirect" required>
<button class="btn btn-primary">Crear credenciales para ChatGPT</button></form>
<p class="small mt-2 mb-0">El ID y el secreto aparecerán arriba una sola vez. Pégalos en ChatGPT con <code>client_secret_basic</code> y el ámbito <code>musedock:read</code>; completa después la autorización en este panel. Para probar, pide «consulta Mortadelo y lista los nodos Filemon y Nitro».</p>
</details>
<?php endif; ?>
<details class="mcp-section"><summary>Redes de los proveedores</summary><p class="small">Se actualizan desde fuentes oficiales. Una actualización fallida conserva la última lista válida; transcurridos siete días se bloquea ese proveedor. Los rangos se aplican a este subdominio y no se añaden al firewall general. Las rutas de autorización y metadatos deben poder abrirse desde tu navegador.</p>
<?php foreach($d['ranges'] as $provider=>$range): ?><div class="d-flex flex-wrap align-items-center gap-2 mb-2"><strong><?= $provider==='openai'?'OpenAI':'Anthropic' ?></strong><span><?= (int)$range['count'] ?> rangos · <?= $range['checked_at']?View::e(gmdate('Y-m-d H:i',$range['checked_at']).' UTC'):'Sin comprobar' ?></span><a href="<?= View::e($range['source']) ?>" target="_blank" rel="noopener noreferrer">Fuente oficial</a><form method="post" action="/settings/mcp/direct/save"><?= View::csrf() ?><input type="hidden" name="action" value="refresh"><input type="hidden" name="provider" value="<?= View::e($provider) ?>"><button class="btn btn-sm btn-outline-secondary">Actualizar rangos</button></form></div><?php endforeach; ?>
</details>
<?php if($d['clients']): ?><h6 class="mb-3">Clientes y permisos</h6><div class="table-responsive"><table class="table"><thead><tr><th>Cliente</th><th>Estado y permisos</th><th>Última consulta</th><th></th></tr></thead><tbody>
<?php foreach($d['clients'] as $id=>$client): ?><tr><td><?= View::e($client['name']) ?> · <?= View::e($client['provider']) ?><br><code><?= View::e($id) ?></code> <button type="button" class="btn btn-sm btn-outline-secondary" data-mcp-copy="client-id-<?= View::e($id) ?>" aria-label="Copiar ID del cliente">Copiar ID</button><input type="hidden" id="client-id-<?= View::e($id) ?>" value="<?= View::e($id) ?>"><br><small>Devolución: <?= View::e($client['redirect_uri']) ?></small></td><td><span class="badge <?= !$client['enabled']?'bg-secondary':(!in_array('musedock:read',$client['scopes']??[],true)?'bg-warning text-dark':'bg-success') ?>"><?= !$client['enabled']?'Revocado':(!in_array('musedock:read',$client['scopes']??[],true)?'Lectura suspendida':($d['enabled']?'Habilitado':'Preparado')) ?></span><form method="post" action="/settings/mcp/direct/save" class="mt-2"><?= View::csrf() ?><input type="hidden" name="action" value="permissions" data-mcp-permissions-marker><input type="hidden" name="client" value="<?= View::e($id) ?>">
<label class="form-check"><input class="form-check-input" type="checkbox" name="allow_read" value="1" <?= in_array('musedock:read',$client['scopes']??[],true)?'checked':'' ?> <?= !$client['enabled']?'disabled':'' ?>> <span class="form-check-label">Permitir lectura</span></label>
<label class="form-check"><input class="form-check-input" type="checkbox" name="allow_write" value="1" <?= in_array('musedock:write',$client['scopes']??[],true)?'checked':'' ?> <?= !$client['enabled']?'disabled':'' ?>> <span class="form-check-label">Permitir solicitar escritura</span></label>
<label class="form-check"><input class="form-check-input" type="checkbox" name="allow_dns" value="1" <?= in_array('musedock:dns',$client['scopes']??[],true)?'checked':'' ?> <?= !$client['enabled']?'disabled':'' ?>> <span class="form-check-label">Permitir solicitar cambios DNS</span></label>
<small>Ámbitos para el asistente: <code><?= View::e(implode(' ',$client['scopes']??[])) ?></code></small>
<button class="btn btn-sm btn-outline-primary mt-2" <?= !$client['enabled']?'disabled':'' ?>>Guardar permisos</button></form></td><td><?= View::e((new \MuseDockPanel\DirectMcp\Registry())->clientStore($id)->get('last_used','Sin consultas')) ?></td><td><form method="post" action="/settings/mcp/direct/save"><?= View::csrf() ?><input type="hidden" name="action" value="disconnect"><input type="hidden" name="client" value="<?= View::e($id) ?>"><button class="btn btn-sm btn-outline-danger" <?= !$client['enabled']?'disabled':'' ?>>Revocar cliente</button></form></td></tr><?php endforeach; ?>
</tbody></table></div><?php endif; ?>
<p class="small text-muted">Operaciones disponibles: dominios y alias de correo, buzones, selector DKIM, bases de datos, redirecciones y DNS. No se ofrecen borrados, cambios de firewall ni administración del clúster. Cambiar permisos invalida los tokens, consentimientos y cambios pendientes del cliente. Guarda y vuelve a autorizar el asistente solicitando los ámbitos que aparecen en su ficha. Escritura requiere lectura; DNS requiere escritura. Cada cambio se aprueba aquí antes de ejecutarse. También deben estar habilitados los permisos generales correspondientes en «Token y SSH · Avanzado».</p><?php $pendingRegistry=new \MuseDockPanel\DirectMcp\Registry(); foreach($d['clients'] as $pendingClientId=>$pendingClient): foreach($pendingRegistry->clientStore($pendingClientId)->pendingOperations() as $operation): $op=$operation['payload']; ?>
<div class="mcp-section"><h6>Cambio pendiente · <?= View::e($pendingClient['name']) ?></h6><p>Herramienta: <code><?= View::e($op['tool']) ?></code> · Caduca 10 minutos después de solicitarlo.</p>
<details open><summary>Plan que vas a aprobar</summary><pre class="small p-3" style="white-space:pre-wrap;overflow-wrap:anywhere"><?= View::e(json_encode($op['plan'],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)) ?></pre></details>
<form method="post" action="/settings/mcp/direct/save" class="d-flex gap-2 flex-wrap"><?= View::csrf() ?><input type="hidden" name="client" value="<?= View::e($pendingClientId) ?>"><input type="hidden" name="request" value="<?= View::e($operation['id']) ?>"><button class="btn btn-warning" name="action" value="approve_write" data-mcp-approve>Confirmar y ejecutar este plan</button><button class="btn btn-outline-secondary" name="action" value="reject_write">Rechazar</button></form></div>
<?php endforeach; endforeach; ?>
<details class="mcp-section"><summary>Añadir un cliente OAuth independiente</summary><form method="post" action="/settings/mcp/direct/save" class="mt-3"><?= View::csrf() ?><input type="hidden" name="action" value="register">
<div class="row g-3"><div class="col-md-6"><label class="form-label">Nombre del cliente</label><input class="form-control" name="name" maxlength="100" placeholder="Mi ChatGPT o Mi Claude" required></div><div class="col-md-6"><label class="form-label">Proveedor</label><select class="form-select" name="provider"><option value="openai">ChatGPT (OpenAI)</option><option value="anthropic">Claude / Anthropic</option><option value="other">Otro cliente MCP compatible</option></select></div><div class="col-12"><label class="form-label">Devolución de llamada exacta mostrada por el asistente</label><input class="form-control" type="url" name="redirect_uri" placeholder="Copia la URL HTTPS de devolución del asistente" required></div><div class="col-12"><label class="form-label">Rangos de salida para otros clientes (CIDR, uno por línea)</label><textarea class="form-control" name="cidrs" rows="3" placeholder="Solo para «Otro cliente»: rangos fiables comprobados por el administrador"></textarea></div></div>
<p class="small mt-3">Sin comodines en las devoluciones OAuth. Otros asistentes necesitan soporte MCP HTTP y OAuth con PKCE S256, además de rangos fiables o IP de salida fija. Las credenciales y los consentimientos son independientes.</p><button class="btn btn-primary" <?= !$d['issuer']?'disabled':'' ?>>Crear credenciales de solo lectura</button></form></details>
<?php if($d['enabled']): ?><form method="post" action="/settings/mcp/direct/save" class="mt-3"><?= View::csrf() ?><input type="hidden" name="action" value="disconnect"><button class="btn btn-danger">Desconectar todo el acceso directo</button></form><?php endif; ?>
</div></div>
